---
- name: Instalar Docker correctamente
  hosts: all
  become: true
  vars:
    docker_user: "{{ ansible_user }}"

  tasks:
    - name: Instalar Docker en RedHat
      block:
        - name: Agregar repositorio Docker
          ansible.builtin.yum_repository:
            name: docker-ce
            description: Docker CE
            baseurl: https://download.docker.com/linux/centos/$releasever/$basearch/stable
            gpgkey: https://download.docker.com/linux/centos/gpg
            enabled: true
            gpgcheck: true

        - name: Instalar Docker CE
          ansible.builtin.dnf:
            name:
              - docker-ce
              - docker-ce-cli
              - containerd.io
            state: present

        - name: Asegurar directorio /etc/docker
          ansible.builtin.file:
            path: /etc/docker
            state: directory
            mode: 0755

      when: ansible_os_family == 'RedHat'

    - name: Instalar Docker en Debian/Ubuntu
      block:
        - name: Instalar dependencias
          ansible.builtin.apt:
            name:
              - apt-transport-https
              - ca-certificates
              - curl
              - gnupg
              - software-properties-common
            update_cache: true

        - name: Agregar clave GPG oficial
          ansible.builtin.apt_key:
            url: https://download.docker.com/linux/ubuntu/gpg
            state: present

        - name: Agregar repositorio Docker
          ansible.builtin.apt_repository:
            repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
            state: present

        - name: Instalar Docker CE
          ansible.builtin.apt:
            name:
              - docker-ce
              - docker-ce-cli
              - containerd.io
            update_cache: true
            state: present

      when: ansible_os_family == 'Debian'

    - name: Habilitar e iniciar servicio Docker
      ansible.builtin.systemd:
        name: docker
        enabled: true
        state: started

    - name: Agregar usuario al grupo Docker
      ansible.builtin.user:
        name: "{{ docker_user }}"
        groups: docker
        append: true
