---
- name: Generar archivo /etc/hosts en todos los nodos
  hosts: all
  become: yes
  vars:
    domain: aula11.local

  tasks:
    - name: Crear archivo hosts usando plantilla
      ansible.builtin.template:
        src: /home/vagrant/templates/hosts.j2
        dest: /etc/hosts
        owner: root
        group: root
        mode: '0644'
