#version: '3.8'

services:
  app:
    build: ./app
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URI=sqlite:////app/data/users.db
    volumes:
      - data_volume:/app/data

volumes:
  data_volume:
